### ISSUE TITLE
Project not working with JHipster v8.9?

### ISSUE THREAD

**Issue by mado89** [Ebsan/generator-jhipster-es-entity-reindexer#10]
When trying your project with current v8.9 the generator fails with the following error message:
```Error  

Cannot find module '/xxxx/project-jhipster/node_modules/generator-jhipster/dist/generators/generator-base/index.js'

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('MODULE_NOT_FOUND')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at process.exit (node:internal/process/per_thread:179:24)
    at onError (/usr/lib/node_modules/yo/lib/cli.js:117:11)
    at /usr/lib/node_modules/yo/lib/cli.js:145:31
```
